# 基本配置
server:
  port: 8010
spring:
  application:
    name: alibaba-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.77:3306/alibaba?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.77:8848
    sentinel:
      transport:
        port: 8888
        dashboard: localhost:8088

# MP配置
mybatis-plus:
  type-aliases-package: com.alibaba.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# OpenFeign
feign:
  sentinel:
    enabled: true

