server:
  port: 8001 # 项目端口号

spring:
  application:
    name: alibaba-rabbitmq # 项目名
  rabbitmq:
    host: 192.168.44.77 # RabbitMQ服务端IP地址
    port: 5672 # RabbitMQ端口号
    username: admin # RabbitMQ管控台账号
    password: admin # RabbitMQ管控台账号


