server:
  port: 8002 # 端口号

spring:
  application:
    name: alibaba-rocketmq # 服务名

rocketmq:
  name-server: 192.168.44.77:9876 # RocketMQ的NameSrv服务地址
  producer:
    group: my-producer-group
    send-message-timeout: 10000

