server:
  port: 8000

spring:
  application:
    name: alibaba-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.77:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-route
          uri: lb://alibaba-user
          order: 1
          predicates:
            - Path=/user-app/**
            - Age=16,80
          filters:
            - StripPrefix=1
            - AddRequestHeader=a,1
            - AddRequestParameter=b,2
            - AddResponseHeader=c,3
            - SetResponseHeader=d,4
            - SetStatus=2000
            - Req=true,true
        - id: order-route
          uri: lb://alibaba-order
          order: 1
          predicates:
            - Path=/order-app/**
          filters:
            - StripPrefix=1
        - id: product-route
          uri: lb://alibaba-product
          order: 1
          predicates:
            - Path=/product-app/**
          filters:
            - StripPrefix=1
  zipkin:
    base-url: http://192.168.44.77:9411 # Zipkin服务端地址
    discovery-client-enabled: false # 不向Nacos注册此服务
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分比设置为100%采样