server:
  port: 5222 # 端口号
spring:
  application:
    name: consumer # 项目名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.77:8848 # Nacos地址
dubbo:
  protocol:
    name: dubbo # 使用dubbo协议，默认
    port: -1 # 自增内部通信端口
  registry:
    address: nacos://192.168.44.77:8848 # Nacos地址
  consumer:
    timeout: 3000 # 消费超时毫秒数，默认1000毫秒
    retries: 0 # 重试次数
    check: false # 启动本项目时，不检查依赖的下游服务以避免启动报错